spring:
  profiles:
    active: dev
server:
  port: 9090
  servlet:
    context-path: /api

# Knife 后端接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /paiad/api-docs

# knife4j 的增强配置
knife4j:
  enable: true
#  basic:
#    enable: true # 进入界面是否需要账号密码
#    username: 0zrthhci
#    password: 71d1c3a6
  setting:
    language: zh_cn

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



